### ISSUE TITLE
WARNING: Unsupported Kotlin plugin version.

### ISSUE THREAD

**Issue by heesung6701** [TodayDoneDone/donedone-android#12]
### 체크리스트

- [X] 제목을 입력하셨나요?
- [X] Assignee를 지정하셨나요?
- [X] 프로젝트를 지정하셨나요?
- [X] 이 DEEP에 맞는 label을 지정하셨나요? (deep-automation, deep-library, deep-product)

### 요약

DoneDone 프로젝트 빌드 시  kotlin 18.10 을 사용하도록 Warning 메세지가 나오고 있습니다.

```
The `embedded-kotlin` and `kotlin-dsl` plugins rely on features of Kotlin `1.8.10` that might work differently than in the requested version `1.8.21`.
```

그레이들 버전 (8.1.1)의 kotlin-dsl 은 1.8.10를 의존하고 있다고 명시 되어 있습니다.
 
그레이들 버전에 따라서 내장된 코틀린 버전이 존재하는데 8.X의 경우 1.8.10을 임베딩 하고 있습니다.

https://docs.gradle.org/current/userguide/compatibility.html#kotlin

따라서 kotlin 1.8.21를 반드시 사용해야 하는 상황이 아니라면 권장 버전인 1.8.10으로 다운 그레이드 하는 안건에 대해서 의견 올려 보았습니다.

### 필요한 이유

Warning 메세지를 보면 그레이들 8.X는 kotlin 1.8.10과 동작하도록 개발 되어서 1.8.21과 동작을 보장하지 않는 것으로 보인다. (?)

### 목표

- kotlin 버전을 유지(1.8.21) 할지 다운그레이드(1.8.10)할지 의견 공유
- 의견에 따라서 작업 진행 (변경 ? 변경 후 PR 진행 : 이슈 클로즈)

### 계획

- kotlin 버전에 대해서 의견을 나눈다.

### 논의 사항

kotlin 버전 논의 진행
1. 1.8.21
2. 1.8.10

**Comment by jisungbin** [comment]
아 저거 경고 신경쓰시는 군여 ㅋㅋㅋ 전 저거 항상 무시해서 그냥 지나쳤었네요
제 경험상 저거 무시해서 생긴 문제는 아직까진 없었어요
근데 코틀린 버전 1.8.10 -> 1.8.20 에 큰 변경 사항은 없던걸로 기억해서 경고 거슬리신다면 내려도 괜찮습니다!

**Comment by heesung6701** [comment]
> > kotlin 버전 논의 진행
> 
> 동작하지 않는다면 1.8.10로 다운그레이드 하는게 좋아보여요

동작은 정상적으로 합니다! 그리고 코틀린이 하위호환성 가져가면서 버전 업그레이드 할거라 이슈는 안생길거라고 생각하긴합니다.

**Comment by heesung6701** [comment]
> 아 저거 경고 신경 쓰시는군요 ㅋㅋㅋ 전 저거 항상 무시해서 그냥 지나쳤었네요
> 제 경험상 저거 무시해서 생긴 문제는 아직까진 없었어요
> 근데 코틀린 버전 `1.8.10` -> `1.8.20`에 큰 변경 사항은 없던 걸로 기억해서 경고 거슬리신다면 내려도 괜찮습니다!

앞으로도 문제는 없을거 같긴합니다. 코틀린이 갑작스럽게 변경되기 전까지는!

경고 메세지를 볼거냐 안보냐 차이 일거 같네요!

**Comment by jisungbin** [comment]
전 항상 경고 메시지를 보면서 해왔기에 @heesung6701 @oPONYOo 여러분의 선택에 맡기겠습니당

**Comment by oPONYOo** [comment]
동작한다면 저는 상관없습니다.
