### ISSUE TITLE
Waffle Basic Widget 추가

### ISSUE THREAD

**Issue by heesung6701** [TodayDoneDone/donedone-android#16]
### 체크리스트

- [X] 제목을 입력하셨나요?
- [X] Assignee를 지정하셨나요?
- [X] 프로젝트를 지정하셨나요?
- [X] 이 DEEP에 맞는 label을 지정하셨나요? (deep-automation, deep-library, deep-product)

### 요약

ViewInflator에 의해서 변경될 수 있는 View에 대해서 WaffleView 클래스를 생성한다.
(GUI 적용은 하지 않고, 클래스만 만들어 둔다.)

### 필요한 이유

Waffle 디자인 시스템은 ViewInflator로 제공될 수 있는 뷰에 대해서는 최대한 활용하고자 한다.
따라서 ViewInflator에 의해서 변경될 수 있는 뷰 클래스를 미리 만들어 둔다.

### 목표

Button은 이미 만들 었고, 아래 위젯 별 클래스 생성.
생성되는 위젯은 기본 동작 및 테마를 따르도록 구현

- [ ] TextView
- [ ] ImageView
- [ ] EditText
- [ ] Spinner
- [ ] ImageButton
- [ ] CheckBox
- [ ] RadioButton
- [ ] CheckedTextView
- [ ] AutoCompleteTextView
- [ ] MultiAutoCompleteTextView
- [ ] RatingBar
- [ ] SeekBar
- [ ] ToggleButton

### 추후 목표

GUI가이드에 따라서 위젯별 GUI 적용 작업 진행

### 계획

위젯별 커스텀 클래스를 만들고 커밋 적용

### 논의 사항

WaffleWidget이라는 용어가 아래 2가지 경우를 모두 포함하는 것 같은데, 이를 나눠서 가져갈지, 그냥 뭉등그려서 가져갈지 의견이 궁금합니다!
1. 안드로이드에서 제공되는 기본 위젯이지만 Waffle에서는 별도 정책이 적용된 위젯
2. 안드로이드에서 제공되지 않는 위젯으로 Waffle에서 별도 구현한 위젯

**Comment by oPONYOo** [comment]
> WaffleWidget이라는 용어가 아래 2가지 경우를 모두 포함하는 것 같은데, 이를 나눠서 가져갈지, 그냥 뭉등그려서 가져갈지 의견이 궁금합니다!


나눠서 가져가면 더 명확해보여서 좋을 것 같아요

**Comment by jisungbin** [comment]
1. `ViewInflator`로 뷰를 교체하는 작업이 필요할까요? 우리는 기존 뷰 시스템을 와플 뷰로 옮기는 구조가 아니라, 맨 처음부터 와플로 UI 작업을 하는 구조가 될텐데 이러면 커스텀 `ViewInflator`로 누릴 수 있는 이점이 무엇인지 궁금해요!
2. 두 가지 모두 `WaffleWidget` 이름을 사용하면 어떨까요? 어쨌든 두 가지 모두 와플이가 새로 정의한 뷰니깐요.

**Comment by heesung6701** [comment]
> 1. `ViewInflator`로 뷰를 교체하는 작업이 필요할까요? 우리는 기존 뷰 시스템을 와플 뷰로 옮기는 구조가 아니라, 맨 처음부터 와플로 UI 작업을 하는 구조가 될텐데 이러면 커스텀 `ViewInflator`로 누릴 수 있는 이점이 무엇인지 궁금해요!
> 2. 두 가지 모두 `WaffleWidget` 이름을 사용하면 어떨까요? 어쨌든 두 가지 모두 와플이가 새로 정의한 뷰니깐요.

Widget내 Button, TextView가 들어가있는 경우 (ex. alertDialog) xml이 라이브러리 내에 있어서 변경을 못해서 커스텀xml을 만들어서 적용시켜야 합니다! 위젯에 따라서 가능한게 있어 불가능한게 있을거같은데 (이부분은 추가확인 필요할거같습니다) , viewInflater를 사용하면 해당케이스에도 모두 WaffleButton WaffleTextBiew로 생성되는 이점이 있습니다. 즉 Xml에서 Button을 WaffleButton으로 변경 되면서 라이브러리에서 제공되는 xml도 치환을 해줍니다!

**Comment by heesung6701** [comment]
> > 1. `ViewInflator`로 뷰를 교체하는 작업이 필요할까요? 우리는 기존 뷰 시스템을 와플 뷰로 옮기는 구조가 아니라, 맨 처음부터 와플로 UI 작업을 하는 구조가 될텐데 이러면 커스텀 `ViewInflator`로 누릴 수 있는 이점이 무엇인지 궁금해요!
> > 2. 두 가지 모두 `WaffleWidget` 이름을 사용하면 어떨까요? 어쨌든 두 가지 모두 와플이가 새로 정의한 뷰니깐요.
> 

1. Widget내 Button, TextView가 들어가있는 경우 (ex. alertDialog) xml이 라이브러리 내에 있어서 변경을 못해서 커스텀xml을 만들어서 적용시켜야 합니다! 위젯에 따라서 가능한게 있어 불가능한게 있을거같은데 (이부분은 추가확인 필요할거같습니다) , viewInflater를 사용하면 해당케이스에도 모두 WaffleButton WaffleTextBiew로 생성되는 이점이 있습니다. 즉 Xml에서 Button을 WaffleButton으로 변경 되면서 라이브러리에서 제공되는 xml도 치환을 해줍니다!

1. WaffleWidget으로 통일하고 구분 안하는게 좋을거같네ㅣ요

**Comment by jisungbin** [comment]
@heesung6701 

> 라이브러리에서 제공되는 xml도 치환을 해줍니다!

라이브러리에서 제공되는 XML을 와플뷰로 바꾸게 되면, 라이브러리에 있던 뷰에 적용할 와플 속성은 어떻게 결정되나요?

**Comment by heesung6701** [comment]
> @heesung6701 
> 
> > 라이브러리에서 제공되는 xml도 치환을 해줍니다!
> 
> 라이브러리에서 제공되는 뷰를 와플 뷰로 바꾸게 되면, 라이브러리에 있던 뷰에 적용할 와플 속성은 어떻게 결정되나요?

라이브러리에 커스텀 attr은 적용 못하겠네요.
ViewInflator에서 주입해주는 방법 뿐일거같은데 음... 별로 실효성 없을거같긴하네요. 

ViewInflator는 필요한 순간이 생기면 그때 고민해도 될거같습니다!!

**Comment by heesung6701** [comment]
디자인 시스템 만들거라 외부 ui 라이브러리 고민할 필요는 없을거같네요ㅎㅎ

**Comment by heesung6701** [comment]
ViewInflator 장점은 xml에서 waffleButton대신 Button을 써서 xml 코드를 줄여준다 정도 인거같습니다:)

**Comment by jisungbin** [comment]
> ViewInflator에서 주입해주는 방법 뿐일거같은데 음... 별로 실효성 없을거같긴하네요. ViewInflator는 필요한 순간이 생기면 그때 고민해도 될거같습니다!!

굿!

**Comment by heesung6701** [comment]
> > WaffleWidget이라는 용어가 아래 2가지 경우를 모두 포함하는 것 같은데, 이를 나눠서 가져갈지, 그냥 뭉등그려서 가져갈지 의견이 궁금합니다!
> 
> 나눠서 가져가면 더 명확해보여서 좋을 것 같아요

엇 이 커멘트를 지금 확인 했네요..! 그러면 안드로이드 회의 때 이야기 해보면 좋을 거 같습니다!

**Comment by heesung6701** [comment]
WaffleViewInflator를 굳이 활용하지 않고 작업을 진행하기 때문에, 위 컴포넌트에 대해서 미리 만들 필요가 없어서 close합니다

**Comment by heesung6701** [comment]
WaffleViewInflator를 굳이 활용하지 않고 작업을 진행하기 때문에, 위 컴포넌트에 대해서 미리 만들 필요가 없어서 close합니다

**Comment by heesung6701** [comment]
WaffleViewInflator를 굳이 활용하지 않고 작업을 진행하기 때문에, 위 컴포넌트에 대해서 미리 만들 필요가 없어서 close합니다
