### ISSUE TITLE
Waffle catalog (waffle-preview) 서브 모듈 생성

### ISSUE THREAD

**Issue by heesung6701** [TodayDoneDone/donedone-android#23]
### 체크리스트

- [X] 제목을 입력하셨나요?
- [X] Assignee를 지정하셨나요?
- [X] 프로젝트를 지정하셨나요?
- [X] 이 DEEP에 맞는 label을 지정하셨나요? (deep-automation, deep-library, deep-product)

### 요약

Waffle 모듈을 확인할 수 있는 샘플 앱을 생성 한다.

### 필요한 이유

waffle 테스트 코드로는 확인 이 어렵고, donedone-android를 수정하며 확인하는 것에는 한계가 있다.
따라서 waffle widget 생성 이후 이를 확인할 수 있는 서브 모듈을 생성한다.

### 목표

waffle widget를 확인할 수 있는 샘플 앱 구현

### 계획

- 서브 모듈 명 정의
- 서브 모듈 생성
- 메인 페이지 구현
- Button 샘플 페이지 구현

### 논의 사항

waffle-preview, waffle-catalog 무엇이 더 적절할 까요?

**Comment by oPONYOo** [comment]
> waffle-preview, waffle-catalog 무엇이 더 적절할 까요?

미리 확인하는 의미에서 waffle-preview가 적절해보여요

**Comment by jisungbin** [comment]
진아님 의견에 :+1: 합니다.

**Comment by heesung6701** [comment]
> > waffle-preview, waffle-catalog 무엇이 더 적절할 까요?
> 
> 미리 확인하는 의미에서 waffle-preview가 적절해보여요

의견 감사합니다!
:waffle:preview 로 작업 진행 하겠습니다!
