### ISSUE TITLE
WaffleCountView

### ISSUE THREAD

**Issue by heesung6701** [TodayDoneDone/donedone-android#27]
### 체크리스트

- [X] 제목을 입력하셨나요?
- [X] Assignee를 지정하셨나요?
- [X] 프로젝트를 지정하셨나요?
- [X] 이 DEEP에 맞는 label을 지정하셨나요? (deep-automation, deep-library, deep-product)

### 요약

아래 컴포넌트 커스텀 뷰로 만들어 보기

⚠: 디자인 변경 시라질 수 있음

| empty | normal | alert |
|:---|:---|:---|
| <img width="49" alt="스크린샷 2023-06-11 오후 7 53 56" src="https://github.com/TodayDoneDone/donedone-android/assets/9072200/fed0d235-d762-4312-957d-3c4d5f782a97"> | <img width="84" alt="스크린샷 2023-06-11 오후 7 53 47" src="https://github.com/TodayDoneDone/donedone-android/assets/9072200/bde0594f-2772-4953-bdc9-1b0df8b552fc"> | <img width="55" alt="스크린샷 2023-06-11 오후 7 54 03" src="https://github.com/TodayDoneDone/donedone-android/assets/9072200/eed3dadc-83bc-4ba6-ae7a-7955ebd2de31">
 |

### 필요한 이유

WaffleTextInput에서 필요할 것으로 보였으나, 아래 화면을 보면 TextInputLayout 영역과 태그 영역이 겹쳐지기 때문에
하나의 뷰로 보기는 어렵고 EditText와 TextCount 뷰는 별도 뷰로 봐야 함

<img width="225" alt="스크린샷 2023-06-11 오후 7 56 59" src="https://github.com/TodayDoneDone/donedone-android/assets/9072200/9c30d625-4857-4338-9f04-f74e18686deb">

### 목표

- WaffleTextCountView 구현한다.

### 계획

- [ ] WaffleCircularDrawable 구현 <img width="14" alt="스크린샷 2023-06-11 오후 7 58 31" src="https://github.com/TodayDoneDone/donedone-android/assets/9072200/8fa7aa4d-caac-46d9-8935-e1634123ca10">

- [ ] WaffleTextCountView 구현

- [ ] Preview 화면 구현

- [ ] 테스트 코드 작성

### 논의 사항

클래스 명 피드백 부탁드립니다..

**Comment by heesung6701** [comment]
WaffleTextCountView  -> WaffleCountView 가 더 좋을 거 같네요

**Comment by jisungbin** [comment]
> TextInputLayout 영역과 태그 영역이 겹쳐지기 때문에

TextInputLayout 영역과 태그 영역이 겹처진다는 말이 이해가 안가요 :sob:

**Comment by heesung6701** [comment]
<img width="828" alt="image" src="https://github.com/TodayDoneDone/donedone-android/assets/9072200/6a150d74-c387-4a78-ac6e-e9e790adaba5">

EditText와 카운트 뷰를 합치면 파란색 네모 인데 초록색 네모가 태그라고 하면 영역으로 잡을 때 겹치는 부분이 생기는 점에 대해서 이야기 한 거 였습니다!

**Comment by jisungbin** [comment]
아하 설명 감사합니다! 이해되었어요. 다만 저는 다르게 생각되는 부분이 있는데요!

> TextInputLayout 영역과 태그 영역이 겹쳐지기 때문에 하나의 뷰로 보기는 어렵고 EditText와 TextCount 뷰는 별도 뷰로 봐야 함

영역이 겹쳐서 하나의 뷰로 보기 어렵다기 보다는, 각각 도메인이 아예 다른 컴포넌트라 하나의 뷰로 보기 어렵다고 생각해요.

<img width="400" src="https://github.com/TodayDoneDone/donedone-android/assets/9072200/9c30d625-4857-4338-9f04-f74e18686deb">

위 뷰를 원자 단위로 쪼개보면 아래와 같이 4가지가 나오는데요,

- 텍스트 입력칸
- 텍스트 입력칸 trailing button(icon)
- 태그 리스트
- 텍스트 길이 검증

여기에서 하나로 묶을 수 있는 원자를 고른다면 같은 도메인인 "텍스트"를 갖는 `텍스트 입력칸`, `텍스트 입력칸 trailing button(icon)`, `텍스트 길이 검증`이 될 거 같아요. 태그는 텍스트와는 아예 다른 도메인이니 하나로 묶기엔 한계가 있을 거 같거든요.
