### ISSUE TITLE
WafflePreview DexFile 로직을 intent-filter로 대체

### ISSUE THREAD

**Issue by heesung6701** [TodayDoneDone/donedone-android#29]
### 체크리스트

- [X] 제목을 입력하셨나요?
- [X] Assignee를 지정하셨나요?
- [X] 프로젝트를 지정하셨나요?
- [X] 이 DEEP에 맞는 label을 지정하셨나요? (deep-automation, deep-library, deep-product)

### 요약

WafflePreview에서 사용한 DexFile은 Deprecated된 api로
<intent-filter> 를 이용하는 방법으로 변경 한다.

### 목표

WafflePreview에서 사용한 DexFile 대신 <intent-filter> 를 이용하도록 변경 한다.

### 계획

- <intent-filter> 카테고리 명 추가
- DexFile 로직을 packageManager + intent-filer로 대체

### 논의 사항

WaffleSample 애노테이션에 있는 정보를 이용해서 리스트에서 보여질 이름과 액티비티 타이틀을 설정하려고 하는데 
의견 궁금합니다!

액티비티 타이틀 설정하기 위해서 BaseActivity 만들고 각 액티비티는 BaseActivity를 상속하는 구조로 바꿀 거 같습니다.
BaseActivity 는 intent에서 EXTRA_TITLE을 받아서 타이틀 설정을 하고 뒤로가기 추가, 메뉴 추가를 할 거 같습니다.

**Comment by jisungbin** [comment]
> WafflePreview에서 사용한 DexFile은 Deprecated된 api로
> 를 이용하는 방법으로 변경 한다.

> WafflePreview에서 사용한 DexFile 대신 를 이용하도록 변경 한다.

`~를`에서 ~ 부분이 빠졌는데 아마 `packageManager + intent-filer`를 의도하신 거겠죠?!

**Comment by jisungbin** [comment]
`@WaffleSample`로 진행하시려는 방식 좋네요! 이견 없습니다 👍🏼.
