### ISSUE TITLE
build-logic 구현

### ISSUE THREAD

**Issue by jisungbin** [TodayDoneDone/donedone-android#3]
### 체크리스트

- [X] 제목을 입력하셨나요?
- [X] Assignee를 지정하셨나요?
- [X] 프로젝트를 지정하셨나요?
- [X] 이 DEEP에 맞는 label을 지정하셨나요? (deep-automation, deep-library, deep-product)

### 요약

합의된 그레이들 관리 방식에 따라 build-logic 구현을 추가합니다.

### 필요한 이유

증분 빌드를 위해 build-logic을 도입했습니다.

### 목표

`donedone.plugin.$id` 플러그인으로 컨벤션 플러그인에 접근할 수 있게 합니다.

### 계획

컨벤션 플러그인 아이디로 아래 항목을 추가합니다.

- `android-application`: 모듈 환경을 안드로이드 어플리케이션으로 구성합니다.
- `android-library`: 모듈 환경을 안드로이드 라이브러리로 구성합니다.
- `android-gmd`: UI Test를 gradle 단에서 하기 위해 [Gradle Managed Device](https://developer.android.com/studio/test/gradle-managed-devices) 구성을 추가합니다.
- `jvm-kotlin`: 모듈 환경을 JVM 코틀린(`org.jetbrains.kotlin.jvm`)으로 구성합니다.
- `test-junit`: 테스트 환경으로 junit을 추가합니다.
- `test-kotest`: 테스트 환경으로 kotest를 추가합니다.

던던 컨벤션 플러그인 아이디에 쉽게 접근할 수 있도록 `donedone(pluginId: String)` 헬퍼 함수를 추가합니다.

```kotlin
fun PluginDependenciesSpec.quackquack(pluginName: String): PluginDependencySpec =
  id("donedone.plugin.$pluginName")

// donedone("android-application") -> id("donedone.plugin.android-application")
```

### 논의 사항

- JDK 버전을 몇으로 할까요? AGP 8부터는 JDK 17이 사용되긴 합니다.
- 루트 폴더명을 `java`가 아닌 `kotlin`으로 작업하려고 합니다. 모두 괜찮으시죠?

**Comment by jisungbin** [comment]
cc @TodayDoneDone/android-dev

**Comment by heesung6701** [comment]
> JDK 버전을 몇으로 할까요? AGP 8부터는 JDK 17이 사용되긴 합니다.
AGP 8.0 이상을 타겟으로 하고 JDK 17 사용 좋은거 같습니다!

> 루트 폴더명을 java가 아닌 kotlin으로 작업하려고 합니다. 모두 괜찮으시죠?
자바 파일 없을 거 같아서 kotlin으로 가져가도 될 거 같습니다 :)

**Comment by oPONYOo** [comment]
> JDK 버전을 몇으로 할까요? AGP 8부터는 JDK 17이 사용되긴 합니다.

JDK 17 저도 좋습니다.

> 루트 폴더명을 java가 아닌 kotlin으로 작업하려고 합니다. 모두 괜찮으시죠?

넵

**Comment by jisungbin** [comment]
모두 빠른 리뷰 감사합니다!
